version: '2'

services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: 805787217936.dkr.ecr.us-west-2.amazonaws.com/aura-airflow:v10
        restart: always
        depends_on:
            - postgres
        environment:
            LOAD_EX: n
            EXECUTOR: Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver