version: '2.1'

x-shared-environment: &environment
    LOAD_EX: n
    FERNET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    # DATABASE: POSTGRES # Defaults to POSTGRES
    # POSTGRES_USER: airflow
    # POSTGRES_PASSWORD: airflow
    # POSTGRES_DB: airflow

x-celery-environment: &celery-environment
    EXECUTOR: Celery
    # REDIS_PASSWORD: redispass

services:
    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
        #     - PGDATA=/var/lib/postgresql/data/pgdata
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: asaf400/docker-airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            <<: *celery-environment
            <<: *environment
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: asaf400/docker-airflow
        restart: always
        depends_on:
            - redis
        environment:
            <<: *celery-environment
            <<: *environment

        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: asaf400/docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        environment:
            <<: *celery-environment
            <<: *environment
        command: scheduler

    worker:
        image: asaf400/docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        environment:
            <<: *celery-environment
            <<: *environment
        command: worker